name: flutter_screen_recording_web
description: Web platform implementation of flutter_screen_recording
version: 1.0.8
homepage: "https://github.com/Isvisoft/flutter_screen_recording"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screen_recording_platform_interface:
    git:
        url: https://github.com/vahid75hj/flutter_screen_recording.git
        ref: master
        path: flutter_screen_recording_platform_interface

  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebFlutterScreenRecording
        fileName: flutter_screen_recording_web.dart
